name = "Modded Vanilla"
author = "YieldEmpire"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "3c01b5212549ccddf58640950bad9ac9bb262db96dbd4b9c83d442ac734665d4"

[versions]
fabric = "0.19.5"
minecraft = "26.2"
