name = "Modded Vanilla"
author = "YieldEmpire"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "b59dc1eec653b0026d25a73f1b8890788dca24bf35e3df7d0f8352b63e69a0ff"

[versions]
fabric = "0.19.5"
minecraft = "26.2"
