name = "Modded Vanilla"
author = "YieldEmpire"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "1b0f0318fbdd435cf6dc386357c9e4a844f306e759a45c0688ebcc431b2df091"

[versions]
fabric = "0.19.5"
minecraft = "26.2"
