# ---------------------------------------------------------
# ClickMobs Config
# NOTE: RELOAD/RESTART SERVER FOR CHANGES TO TAKE EFFECT
# ---------------------------------------------------------

_version: 7

# Whether to check for updates on server startup. Strongly Recommended.
check_update: true

# ---------------------------------------------------------
# In the following section you can whitelist/blacklist mobs.
# ---------------------------------------------------------
# To whitelist/blacklist a vanilla mob, add its entity name.
#     i.E: "creeper" or "ender_dragon"
# To whitelist/blacklist mobs from other mods, use the full identifier with the namespace.
#     i.E: "othermod:fancy_creeper"
# ---------------------------------------------------------
# You can also use tags (predicates) to whitelist/blacklist mobs with certain properties.
# Available tags are:
#     ?all, ?hostile, ?baby, ?tamed, ?nametagged, ?silent, ?mob
# 
# You can (optionally) pass arguments to certain tags:
#     - ?nametagged(Dinnerbone)
# You can combine multiple tags:
#     - ?tamed ?nametagged
# You can negate tags using "not":
#     - not ?hostile
# You can use the ?mob tag alongside other tags to use tags on specific mobs.
#     - ?mob(creeper, zombie) ?nametagged(Friendly!)
# 
# Check the wiki for more documentation on tags:
# https://github.com/Clickism/ClickMobs/wiki/Tags
# ---------------------------------------------------------

# Mobs that are allowed to be picked up.
# The whitelist takes precedence over the blacklist.
# (Blacklisted mobs included in the whitelist will still be allowed)
whitelisted_mobs:
- cow
- pig
- sheep

# Mobs that are not allowed to be picked up.
blacklisted_mobs:
- ?hostile
- wither
- ender_dragon

# Whether dispensers can dispense picked up mobs.
enable_dispensers: true

# Items that prevent picking up mobs when held in hand.
# Use the (full) item identifiers of the items.
# 
# Harnesses are always blocked for Happy Ghast compatibility
# and do not need to be added here.
# 
# Use the tag "?all" to block all items. This will make it so players
# can only pick up mobs with an empty hand.
# 
# For items from another mod, add the namespace before the item name.
#     i.E: "othermod:otheritem"
blacklisted_items_in_hand:
- lead
- saddle
