[modName]
	# Name: Mod Name Format
	# Description: Formatting for the mod names in tooltips for JEI GUIs. Leave blank to disable.
	# Valid Values: A chat formatting string.
	# Use these formatting colors:
	# BLACK DARK_BLUE DARK_GREEN DARK_AQUA DARK_RED DARK_PURPLE GOLD GRAY DARK_GRAY BLUE GREEN AQUA RED LIGHT_PURPLE YELLOW WHITE
	# With these formatting options:
	# OBFUSCATED BOLD STRIKETHROUGH UNDERLINE ITALIC
	# Default Value: BLUE ITALIC
	modNameFormat = BLUE ITALIC


