# Replace the blockstate neighbor table
replaceNeighborLookup = true
# Do not store the properties of a state explicitly and read themfrom the replace neighbor table instead. Requires replaceNeighborLookup to be enabled
replacePropertyMap = true
# Deduplicate cached data for blockstates, most importantly collision and render shapes
blockstateCacheDeduplication = true
# Save memory overhead from empty data component maps/patched
dataComponentPatch = true
# Replace objects used to detect multi-threaded access to chunks by a much smaller field. This option is disabled by default due to very rare and very hard-to-reproduce crashes, use at your own risk!
useSmallThreadingDetector = false
# Use a slightly more compact, but also slightly slower representation for block states
compactFastMap = false
