#This file stores configuration options for Iris, such as the currently active shaderpack
#Thu Oct 08 12:39:11 PDT 2026
allowUnknownShaders=false
colorSpace=SRGB
disableUpdateMessage=false
enableDebugOptions=false
enableShaders=true
maxShadowRenderDistance=32
shaderPack=ComplementaryUnbound_r5.9.3.zip
