#Client-only settings
[client]
	#Whether the backpack icon should be visible in player's inventory
	showBackpackIconInInventory = true
	#Sends a message to the player on death with backpack coordinates
	sendBackpackCoordinatesMessage = true
	#Enables tip, how to obtain a backpack, if there's no crafting recipe for it
	obtainTips = true
	#Render tools in tool slots on the backpack, while worn
	renderTools = true
	#Only for supporters, option to show/hide the Supporter Star Badge. If you want to receive the Supporter Star Badge, visit my Ko-fi page :)! - https://ko-fi.com/tiviacz1337
	showSupporterBadge = true

	#The position of the Tools Overlay on the screen
	[client.toolsOverlay]
		#If true, the currently held item will be swapped with the selected tool belt slot when closing the tool belt GUI
		swapOnClose = true
		#Displays the full tooltip when hovering over an item in the tool belt. If false, only the item name is shown
		showTooltip = false
		#Render backpack icon in the center of the tools overlay
		renderBackpackIconInCenter = true
		#Overlay opacity
		# Default: 0.75
		# Range: 0.0 ~ 1.0
		opacity = 0.75
		#X offset
		# Default: 0
		# Range: > -2147483648
		offsetX = 0
		#Y offset
		# Default: 0
		# Range: > -2147483648
		offsetY = 0

	#The position of the Overlay on the screen
	[client.overlay]
		#Enables tanks and tool slots overlay, while backpack is worn
		enableOverlay = true
		#Offsets to left side
		# Default: 20
		# Range: > -2147483648
		offsetX = 20
		#Offsets to up
		# Default: 30
		# Range: > -2147483648
		offsetY = 30
