# Don't change this! Version used to track needed updates.
version = 1
items = [
    [ "minecraft:ender_pearl", 64 ],
    [ "minecraft:cake", 16 ],
    [ "#c:armors/horse", 64 ],
    [ "#c:potions", 3 ],
    [ "minecraft:snowball", 64 ],
    [ "#minecraft:harnesses", 16 ],
    [ "#minecraft:boats", 16 ],
    [ "#minecraft:beds", 16 ],
    [ "minecraft:enchanted_book", 64 ],
    [ "#c:music_discs", 64 ],
    [ "#c:eggs", 64 ],
    [ "#sensible_stackables:banner_patterns", 64 ],
    [ "#c:foods/soup", 16 ],
    [ "minecraft:saddle", 16 ],
    [ "#sensible_stackables:minecarts", 16 ]
]
splashPotionCooldown = 1
uncapStackSize = false
commonStackSize = 64